CREATE TABLE "VENUES"(
    "VENUEID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "VENUE_NAME" VARCHAR(255),
    "CAPACITY" INT,
    "LATITUDE" VARCHAR(50),
    "LONGITUDE" VARCHAR(50)
);
CREATE TABLE "VOTES"(
    "VOTEID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "USERID" INT,
    "GIGID" INT
);
CREATE TABLE "COMMENT"(
    "COMMENTID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "USERID" INT,
    "BANDID" INT,
    "GIGID" INT,
    "USERCOMMENT" VARCHAR(255)
);
CREATE TABLE "USERS"(
    "USERID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "USERNAME" VARCHAR(50) UNIQUE,
    "UNAME" VARCHAR(60),
    "BIO" VARCHAR(500),
    "EMAIL" VARCHAR(50) UNIQUE,
    "PICDIR" VARCHAR(80),
    "ISADMIN" VARCHAR(10),
    "PASSWORD" VARCHAR(50),
    "ISBANNED" VARCHAR(10)
);
CREATE TABLE "BAND"(
    "BANDID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "USERNAME" VARCHAR(50),
    "BAND_NAME" VARCHAR(90),
    "BIO" VARCHAR(255),
    "EMAIL" VARCHAR(50),
    "PICDIR" VARCHAR(80),
    "PASSWORD" VARCHAR(50)
);
CREATE TABLE "GIG"(
    "GIGID" INT NOT NULL primary key
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "VENUEID" INT,
    "BANDID" INT,
    "USERID" INT,
    "GIG_DESCRIPTION" VARCHAR(255),
    "DATE_CREATED" VARCHAR(40),
    "GIG_DATE" VARCHAR(20),
    "PRICE" DECIMAL(6,2),
    "ISCONFIRMED" VARCHAR(10)
);